### ISSUE TITLE
[Question] Which Glade version is used for the UIs?

### ISSUE THREAD

**Issue by klei1984** [jestin/gimp-vera-tileset-plugin#1]
Hello @jestin, could you please clarify which Glade version or other UI RAD tool are you using if any?

First I tried latest version of Glade from msys2 which only supports gtk3. Then I tried Glade-3 which supports gtk2, but its widget catalog does not know about gimp specializations like GimpFrame or GimpSpinButton.

Thanks.

**Comment by klei1984** [comment]
In the mean time i figured out that simply renaming Gimp widget specializations to their parent classes resolve loading issues in Glade-3.

**Comment by jestin** [comment]
Sorry, I just now saw this question.

I have not used any GUI tool for the UI.  I simply edit the *.ui files in my text editor.

Also, I apologize for the lack of documentation.  While this tool is functional, I am still tweaking it from time to time to fix bugs.  I'm testing this by using it for other projects and then fixing it up as I go.  I plan to create documentation for both developers and users, but I'm waiting until its more stable and I have more time.
