### ISSUE TITLE
Plugin doesnt seem to work

### ISSUE THREAD

**Issue by adiee5** [jestin/gimp-vera-tileset-plugin#4]
i'm using gimp 2.10.14 on windows pc, i have compiled the plugin using gcc on Windows Subsystem For Linux and used gimptool-2.0 that's built in the gimp in order to --install-bin the compiler output. i've also copied the *.ui files to appropriate location

**Comment by jestin** [comment]
Make sure everything installed correctly by going to to Help -> Procedure Browser and searching for "vera" by name.  If the plugin is installed correctly then you should find the "file-vera-save" procecure:
![image](https://user-images.githubusercontent.com/669174/218583419-91fd155c-110c-4817-bf49-b555e4f62d3c.png)

If not, you may have to go back and make sure everything compiled correctly and ended up in the correct directory.  As far as I know, you are the first one to compile and install on Windows, so I wouldn't be surprised if something was completely broken.  Thanks for trying this out, and I appreciate any help in getting this working under Windows!

**Comment by adiee5** [comment]
well, my procedure browser lacks those, so i might have compiled it wrongly. i sholud probably use gcc for the windows, this's going to be hard to install

**Comment by jestin** [comment]
If you've successfully built the binary, and you have `gimptool-20` installed, try running the install at the command line manually from the source directory:

```
$ gimptool-2.0 --install-bin vera_tileset
$ sudo cp plug-in-file-vera-tiles.ui `gimptool-2.0 --gimpdatadir`/ui/plug-ins/plug-in-file-vera-tiles.ui
$ sudo cp plug-in-file-vera-selector.ui `gimptool-2.0 --gimpdatadir`/ui/plug-ins/plug-in-file-vera-selector.ui
$ sudo cp plug-in-file-vera-bitmap.ui `gimptool-2.0 --gimpdatadir`/ui/plug-ins/plug-in-file-vera-bitmap.ui
```
The first command should copy the compiled binary to the correct directory, and the next three commands will copy the UI resources to the correct directory (you may or may not need `sudo`, or whatever is equivalent on Windows).

My output for the installation step is:

```
$ gimptool-2.0 --install-bin vera_tileset
cp 'vera_tileset' '/home/jestin/.config/GIMP/2.10/plug-ins/vera_tileset/'
```

**Comment by jestin** [comment]
You may also want to check that your version of `gimptool-2.0` is associated with the correct version of the GIMP:
![image](https://user-images.githubusercontent.com/669174/219106646-a8379bc6-79f1-4479-ba02-bc278b56fd5b.png)
If your versions don't match, then `gimptool-2.0` is probably installing the binary and the resources into the wrong place.

**Comment by adiee5** [comment]
> If you've successfully built the binary, and you have `gimptool-20` installed, try running the install at the command line manually from the source directory:
> 
> ```
> $ gimptool-2.0 --install-bin vera_tileset
> $ sudo cp plug-in-file-vera-tiles.ui `gimptool-2.0 --gimpdatadir`/ui/plug-ins/plug-in-file-vera-tiles.ui
> $ sudo cp plug-in-file-vera-selector.ui `gimptool-2.0 --gimpdatadir`/ui/plug-ins/plug-in-file-vera-selector.ui
> $ sudo cp plug-in-file-vera-bitmap.ui `gimptool-2.0 --gimpdatadir`/ui/plug-ins/plug-in-file-vera-bitmap.ui
> ```
> 
> The first command should copy the compiled binary to the correct directory, and the next three commands will copy the UI resources to the correct directory (you may or may not need `sudo`, or whatever is equivalent on Windows).
> 
> My output for the installation step is:
> 
> ```
> $ gimptool-2.0 --install-bin vera_tileset
> cp 'vera_tileset' '/home/jestin/.config/GIMP/2.10/plug-ins/vera_tileset/'
> ```

obviously i did those, at least on windows

**Comment by adiee5** [comment]
but i have to probably somehow to generate windows .exe binary

**Comment by jestin** [comment]
Yes, if that's the part that is failing, then there's no mystery.  I was assuming that you were successfully building the binary, but the plugin wasn't working after installation.

What happens when you run `make`?  _Are_ you running `make`?  Perhaps if you could show me the output when you build and try to install.  I want to make sure I'm addressing the correct problem.

**Comment by adiee5** [comment]
i've installed mingw-w64 on wsl (i think it's capable of generating .EXEs) and tried to compile it, but i get this error on compilation 
![image](https://user-images.githubusercontent.com/58359866/219203020-18f72452-4f0c-44b1-b766-5f961414710a.png)

**Comment by adiee5** [comment]
> What happens when you run `make`? _Are_ you running `make`? Perhaps if you could show me the output when you build and try to install. I want to make sure I'm addressing the correct problem.

i'm not making, i instead do things, that make'd do otherwise, my compiler command's:
```sh
x86_64-w64-mingw32-gcc-win32 -pthread -I/usr/include/gegl-0.4 -I/usr/include/gio-unix-2.0 -I/usr/include/json-glib-1.0 -I/usr/include/babl-0.1 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gimp-2.0 -I/usr/include/libxml2 -Wno-deprecated-declarations -o vera_tileset.exe vera_tileset.c -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lm -Wl,--export-dynamic -lgmodule-2.0 -pthread -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -lxml2
```

**Comment by adiee5** [comment]
when i ran gcc it was all fine, but it was obviously generating unix binaries

**Comment by jestin** [comment]
Maybe we should try a different approach.  Can you download the source for GIMP and attempt to compile that into a Windows binary?

The idea is that it's the same set of dependencies for compiling a gimp plugin, but there's bound to be a LOT more help online for compiling the GIMP for Windows than there is for GIMP plugins.  If you can troubleshoot building GIMP, I'm guessing that building plugins won't be much different.

This guide might get you started:  https://developer.gimp.org/core/setup/build/windows/

**Comment by adiee5** [comment]
WHAT?!

**Comment by adiee5** [comment]
ok, i'll do that, but what's that? 
![image](https://user-images.githubusercontent.com/58359866/219215389-f33011e4-7c71-4758-8466-ea26fdfa8771.png)
is this intended for a make file?

**Comment by adiee5** [comment]
oh, those are just env variables, nevermind

**Comment by adiee5** [comment]
well, i've tried to compile the plugin in msys like in the tutorial, buuut
![image](https://user-images.githubusercontent.com/58359866/219221480-7bcc5a88-4165-4954-a302-3dc7b5819e59.png)
it's still better at least

i haven't compiled the gimp itself

**Comment by adiee5** [comment]
i used hints from [this page](https://www.lprp.fr/2021/06/compiling-gimp-plugins-for-windows-has-never-been-so-easy-with-msys2/) and executed `gimptool-2.0 -n --build vera_tileset.c | sh`, here are the results:
![image](https://user-images.githubusercontent.com/58359866/219252232-c32691d0-2b24-43e5-95af-94c2c3d4c1d5.png)
i've checked for xml packages, but it seems like there are all packages needed. i might try to change the source code maybe to include from `<libxml2/libxml/encoding.h>` instead

**Comment by adiee5** [comment]
lol, internal files also reference the unexisting <libxml/*> path. i'll be better off making the symlink i guess

**Comment by adiee5** [comment]
hmm, that's new (after i've created the symlink)
![image](https://user-images.githubusercontent.com/58359866/219254312-d8373743-0603-451b-9753-5a23c7a0cba1.png)

**Comment by jestin** [comment]
Looks to me like you've fixed the include paths, but now the library paths aren't correct.  Still, nice progress!

**Comment by adiee5** [comment]
```
gcc  -IC:/msys64/mingw64/include/gimp-2.0 -IC:/msys64/mingw64/include/gdk-pixbuf-2.0 -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/webp -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include/gegl-0.4 -IC:/msys64/mingw64/include/gio-win32-2.0 -IC:/msys64/mingw64/include/json-glib-1.0 -IC:/msys64/mingw64/include/babl-0.1 -IC:/msys64/mingw64/include/gtk-2.0 -mms-bitfields -IC:/msys64/mingw64/lib/gtk-2.0/include -IC:/msys64/mingw64/include/pango-1.0 -IC:/msys64/mingw64/include/fribidi -IC:/msys64/mingw64/include/atk-1.0 -DLIBDEFLATE_DLL  -o 'vera_tileset' 'vera_tileset.c'  -mwindows -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lgmodule-2.0 -ljson-glib-1.0 -lbabl-0.1 -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -Wl,-luuid -lpangowin32-1.0 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdi32 -lmsimg32 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lxml2
```
there are no errors with it. exe's here, i hope it'll run

**Comment by adiee5** [comment]
OMG, YESSS!!!!!! It works! 
[vera_tileset.exe.gz](https://github.com/jestin/gimp-vera-tileset-plugin/files/10761465/vera_tileset.exe.gz)

**Comment by jestin** [comment]
That's great!

Furthermore...you've left a nice trail of breadcrumbs in this issue thread that others can probably find it useful!
