### ISSUE TITLE
Windows installation pitfalls

### ISSUE THREAD

**Issue by Frosty-J** [jestin/gimp-vera-tileset-plugin#6]
After a bit of bumbling about, I'm now using this plugin on Windows. Hopefully it won't fall over as soon as I try to do anything for real.

Possible pitfalls:

- `echo " -lxml2" >> win.localcomp.sh` - this appended the argument onto a new line, which upset things.
  - I also did `pacman -S libxml2` as part of my process of doing things until it works, but I think that likely ultimately wasn't necessary.
- [win.apply.bat](https://github.com/jestin/gimp-vera-tileset-plugin/blob/master/win.apply.bat) should probably have quotation marks around the filepaths. Due to the spaces, it has syntax errors if run how it is.

**Comment by jestin** [comment]
If I make these changes, can you test them out?  I don't have a Windows computer to test with, and didn't create the Windows installation instructions/scripts.

Alternatively, if you've made and tested the changes already, could you submit them as a pull request?

I'd love to fix the Windows installation, but I need some help :smiley:

**Comment by Frosty-J** [comment]
I won't go from a clean install, but I can commit these changes easily enough. I may also change `cd gimp-vera*` to `cd gimp-vera-tileset-plugin` since you end up with that from Tab completion anyway.

**Comment by Frosty-J** [comment]
Also, I'm getting it where attempting to export a tile set doesn't do anything. The dialogue just closes after clicking "Export" without proceeding to the next one. If I first export a bitmap, then do a tile set, it works okay. I haven't figured out how to get any info as to why this happens, at least on Windows.
